CREATE DATABASE HoaDon
GO

USE HoaDon
GO

CREATE TABLE Kho
(
	ID_SP VARCHAR(5) PRIMARY KEY,
	TenSP NVARCHAR(40),
	MoTa NVARCHAR(40),
	DonVi NVARCHAR(20),
	Gia VARCHAR(5),
	TonKho VARCHAR(5),
)
GO
INSERT Kho VALUES (1,N'Máy tính T450',N'Máy nhập mới','Chiếc',1000,50)
INSERT Kho VALUES (2,N'Điện thoại Nokia5670',N'Điện thoại đang hot','Chiếc',200,130)
INSERT Kho VALUES (3,N'Máy Tính T450',N'Máy nhập mới','Chiếc',100,23)
GO


CREATE TABLE KhachHang
(
	TenKH NVARCHAR(20) PRIMARY KEY,
	DiaChi NVARCHAR(40),
	SDT VARCHAR(12),
)
GO
INSERT KhachHang VALUES (N'Nguyễn Văn An',N'111 Nguyễn Trãi, Thanh Xuân, Hà Nội',987654321)
GO

CREATE TABLE DonHang
(
	MaDH VARCHAR(5) PRIMARY KEY,
	TenKH NVARCHAR(20) FOREIGN KEY REFERENCES KhachHang(TenKH),
	NgayDH DATE
)
GO
INSERT DonHang VALUES (123,N'Nguyễn Văn An','20091118')
GO

CREATE TABLE ChiTietDH
(
	MaDH VARCHAR(5) FOREIGN KEY REFERENCES DonHang(MaDH),
	MaSP VARCHAR(5) FOREIGN KEY REFERENCES Kho(ID_SP),
	TenSP NVARCHAR(40),
	Gia VARCHAR(5),
	SL VARCHAR(5)
)
GO

